import { useEffect, useState } from 'react'
import { Card, FormField, LoadingState, Money, TextInput } from '../../components/shared'
import { formatCount } from '../../app/formatters'
import { PageHeader, type Locale } from '../../layouts/AppLayout'
import { localDate } from '../../app/formatters'
type Summary={from:string;to:string;salesTotal:number;purchasesTotal:number;expensesTotal:number;receiptsTotal:number;paymentsTotal:number;grossMargin:number;salesCount:number;purchaseCount:number;salesReturnsTotal:number;purchaseReturnsTotal:number}
const reportToday=localDate();const reportStart=localDate(new Date(Date.now()-30*86400000))
export function ReportsPage({locale}:{locale:Locale}){const ar=locale==='ar';const [from,setFrom]=useState(reportStart);const [to,setTo]=useState(reportToday);const [summary,setSummary]=useState<Summary|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [symbol,setSymbol]=useState('');useEffect(()=>{fetch('/api/currencies').then(r=>r.ok?r.json() as Promise<Array<{symbol:string;isPrimary:boolean}>>:[]).then(list=>setSymbol(list.find(c=>c.isPrimary)?.symbol??'')).catch(()=>undefined)},[]);useEffect(()=>{fetch(`/api/reports/summary?from=${from}&to=${to}`).then(async r=>{if(!r.ok)throw new Error('load');return r.json() as Promise<Summary>}).then(setSummary).catch(()=>setError(ar?'تعذر تحميل التقرير.':'Could not load report.')).finally(()=>setLoading(false))},[from,to,ar]);return <div className="settings-page" dir={ar?'rtl':'ltr'}><PageHeader eyebrow={ar?'التقارير':'REPORTS'} title={ar?'التقارير':'Reports'} description={ar?'ملخص الحركة المالية والمبيعات خلال الفترة المحددة.':'Financial and sales summary for the selected period.'}/><Card className="report-filters"><div className="form-grid-fields"><FormField label={ar?'من':'From'}><TextInput type="date" value={from} onChange={e=>{setFrom(e.target.value);setLoading(true)}}/></FormField><FormField label={ar?'إلى':'To'}><TextInput type="date" value={to} onChange={e=>{setTo(e.target.value);setLoading(true)}}/></FormField></div></Card>{error&&<div className="form-error">{error}</div>}{loading?<LoadingState/>:summary&&<div className="report-metrics"><Metric title={ar?'إجمالي المبيعات':'Sales'} value={summary.salesTotal} symbol={symbol}/><Metric title={ar?'مرتجعات المبيعات':'Sales returns'} value={summary.salesReturnsTotal} symbol={symbol}/><Metric title={ar?'إجمالي المشتريات':'Purchases'} value={summary.purchasesTotal} symbol={symbol}/><Metric title={ar?'مرتجعات المشتريات':'Purchase returns'} value={summary.purchaseReturnsTotal} symbol={symbol}/><Metric title={ar?'المنصرفات':'Expenses'} value={summary.expensesTotal} symbol={symbol}/><Metric title={ar?'صافي الهامش التقريبي':'Approx. gross margin'} value={summary.grossMargin} symbol={symbol}/><Metric title={ar?'عدد فواتير البيع':'Sales invoices'} count={summary.salesCount}/><Metric title={ar?'عدد فواتير الشراء':'Purchase invoices'} count={summary.purchaseCount}/></div>}</div>}
function Metric({title,value,symbol,count}:{title:string;value?:number;symbol?:string;count?:number}){return <Card className="kpi-card"><span className="kpi-label">{title}</span><strong className="kpi-value">{count!==undefined?<bdi dir="ltr">{formatCount(count)}</bdi>:<Money value={value??0} symbol={symbol}/>}</strong></Card>}
