import { useEffect, useState } from 'react'
import { Button, ErrorState, FormField, LoadingState, Modal, TextInput } from '../../components/shared'
import type { Locale } from '../../layouts/AppLayout'

type Currency = { currencyId: number; currencyCode: string; currencyNameEn: string; currencyNameAr: string; symbol: string; isPrimary: boolean; isActive: boolean; exchangeRate: number | null; flagBase64: string | null }

export function CurrencyRatesDialog({ open, locale, onClose }: { open: boolean; locale: Locale; onClose: () => void }) {
  const ar = locale === 'ar'; const [rows, setRows] = useState<Currency[]>([]); const [values, setValues] = useState<Record<number, string>>({}); const [original, setOriginal] = useState<Record<number, string>>({}); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  useEffect(() => { if (!open) return; setLoading(true); setError(''); fetch('/api/currencies?includeInactive=true').then(async response => { if (!response.ok) throw new Error(await response.text() || `Request failed (${response.status})`); return response.json() as Promise<Currency[]> }).then(data => { const next: Record<number, string> = {}; data.forEach(item => { next[item.currencyId] = item.exchangeRate === null ? '' : String(item.exchangeRate) }); setRows(data); setValues(next); setOriginal(next) }).catch(reason => setError(reason instanceof Error ? reason.message : (ar ? 'تعذر تحميل أسعار الصرف.' : 'Could not load exchange rates.'))).finally(() => setLoading(false)) }, [open, ar])
  const primary = rows.find(item => item.isPrimary)
  async function save() { const rates = rows.filter(item => !item.isPrimary && item.isActive).map(item => ({ currencyId: item.currencyId, rate: Number(values[item.currencyId]) })).filter(item => Number.isFinite(item.rate) && item.rate > 0 && String(item.rate) !== original[item.currencyId]); setSaving(true); setError(''); try { const response = await fetch('/api/currencies/rates', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ rates }) }); if (!response.ok) throw new Error(await response.text() || `Request failed (${response.status})`); onClose() } catch (reason) { setError(reason instanceof Error ? reason.message : (ar ? 'تعذر حفظ أسعار الصرف.' : 'Could not save exchange rates.')) } finally { setSaving(false) } }
  return <Modal open={open} title={ar ? 'أسعار الصرف' : 'Exchange rates'} description={ar ? 'إدارة أسعار العملات مقابل العملة الأساسية.' : 'Manage currency rates relative to the primary currency.'} closeLabel={ar ? 'إغلاق' : 'Close'} onClose={() => !saving && onClose()} busy={saving} footer={<><Button variant="ghost" disabled={saving} onClick={onClose}>{ar ? 'إلغاء' : 'Cancel'}</Button><Button variant="primary" loading={saving} onClick={() => void save()}>{ar ? 'حفظ التغييرات' : 'Save changes'}</Button></>}>
    {error && <ErrorState title={ar ? 'تعذر تحميل الأسعار' : 'Could not load rates'} detail={error} />}
    {loading ? <LoadingState /> : <div className="currency-rates-form"><p className="currency-rate-base">{ar ? `العملة الأساسية: ${primary?.currencyNameAr ?? '—'} (${primary?.symbol ?? ''})` : `Primary currency: ${primary?.currencyNameEn ?? '—'} (${primary?.symbol ?? ''})`}</p>{rows.filter(item => !item.isPrimary).map(item => <div className="currency-rate-row" key={item.currencyId}><div><strong>{item.flagBase64 && <img className="currency-flag-image" src={item.flagBase64} alt="" />}{ar ? item.currencyNameAr : item.currencyNameEn}</strong><small dir="ltr">{item.symbol} · {item.isActive ? (ar ? 'نشطة' : 'Active') : (ar ? 'غير نشطة' : 'Inactive')}</small></div><FormField label={ar ? `1 ${item.symbol} يساوي` : `1 ${item.symbol} equals`}><TextInput dir="ltr" type="number" min="0.00000001" step="0.00000001" disabled={!item.isActive || saving} value={values[item.currencyId] ?? ''} onChange={event => setValues(current => ({ ...current, [item.currencyId]: event.target.value }))} placeholder={primary?.symbol ?? ''} /></FormField></div>)}<p className="currency-rate-note">{ar ? 'سيتم تسجيل التغييرات فقط في سجل أسعار الصرف.' : 'Only changed rates are recorded in history.'}</p></div>}
  </Modal>
}
