import { useEffect, useMemo, useState } from "react";
import { Button, EmptyState, ErrorState, FormField, IconButton, LoadingState, Modal, SearchInput, Select, StatusBadge, TextInput } from "../../components/shared";
import { PageHeader, type Locale } from "../../layouts/AppLayout";
import { Icon } from "../../components/icons";

type InventoryItem = { itemId: number; itemCode: string; nameAr: string; nameEn: string; baseUnitAr?: string | null; baseUnitEn?: string | null; quantity: number; sellPrice: number; lastPurchasePrice?: number | null; minimumLevelForAlert: number; isActive: boolean };
type Batch = { purchaseLineId: number; invoiceNo: string; purchaseDate: string; barcode?: string | null; expiryDate?: string | null; batchNo: string; quantity: number; availableQuantity: number; unitCost: number };

export function InventoryPage({ locale, branchId, branchName, userId }: { locale: Locale; branchId: number; branchName: string; userId: number }) {
  const ar = locale === "ar";
  const [rows, setRows] = useState<InventoryItem[]>([]), [search, setSearch] = useState(""), [page, setPage] = useState(0), [pageSize, setPageSize] = useState(10), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [batchItem, setBatchItem] = useState<InventoryItem | null>(null), [batches, setBatches] = useState<Batch[]>([]), [batchLoading, setBatchLoading] = useState(false);
  const [disposalBatch, setDisposalBatch] = useState<{ item: InventoryItem; batch: Batch } | null>(null), [disposalQty, setDisposalQty] = useState(""), [disposalReason, setDisposalReason] = useState(""), [disposalSaving, setDisposalSaving] = useState(false);

  async function load() { setLoading(true); setError(""); try { const response = await fetch(`/api/inventory?branchId=${branchId}`); if (!response.ok) throw new Error(await response.text()); setRows(await response.json() as InventoryItem[]); } catch (reason) { setError(reason instanceof Error ? reason.message : (ar ? "تعذر تحميل المخزون." : "Could not load inventory.")); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [branchId]);
  const visible = useMemo(() => { const query = search.trim().toLocaleLowerCase(); return query ? rows.filter(item => [item.itemCode, item.nameAr, item.nameEn].some(value => value.toLocaleLowerCase().includes(query))) : rows; }, [rows, search]);
  const pageCount = Math.max(1, Math.ceil(visible.length / pageSize));
  const pageRows = visible.slice(page * pageSize, (page + 1) * pageSize);
  const format = (value: number) => value.toLocaleString(undefined, { maximumFractionDigits: 3 });
  const date = (value?: string | null) => value ? value.slice(0, 10).split("-").reverse().join("/") : "—";
  const status = (item: InventoryItem) => item.quantity <= 0 ? "danger" : item.quantity <= item.minimumLevelForAlert ? "warning" : "success";

  async function openBatches(item: InventoryItem) { setBatchItem(item); setBatches([]); setBatchLoading(true); try { const response = await fetch(`/api/inventory/${item.itemId}/batches?branchId=${branchId}`); if (!response.ok) throw new Error(await response.text()); setBatches(await response.json() as Batch[]); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load batches."); } finally { setBatchLoading(false); } }
  async function submitDisposal() { if (!disposalBatch || Number(disposalQty) <= 0 || !disposalReason.trim()) return; setDisposalSaving(true); try { const response = await fetch("/api/inventory/disposals", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ itemId: disposalBatch.item.itemId, purchaseLineId: disposalBatch.batch.purchaseLineId, quantity: Number(disposalQty), reason: disposalReason.trim(), requestedBy: userId, branchId }) }); if (!response.ok) throw new Error(await response.text()); setDisposalBatch(null); setDisposalQty(""); setDisposalReason(""); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : (ar ? "تعذر إنشاء طلب الإتلاف." : "Could not create disposal request.")); } finally { setDisposalSaving(false); } }

  return <div className="settings-page inventory-page" dir={ar ? "rtl" : "ltr"}>
    <PageHeader title={ar ? "المخزن" : "Inventory"} description={ar ? `مخزون فرع ${branchName} — الكميات بالوحدة الأساسية.` : `${branchName} branch stock — quantities in the base unit.`} actions={<span className="inventory-branch-badge"><Icon name="inventory" size={17} />{branchName}</span>} />
    <div className="settings-list-toolbar"><SearchInput aria-label={ar ? "بحث في المخزون" : "Search inventory"} placeholder={ar ? "ابحث بالرمز أو اسم الصنف" : "Search by code or item name"} value={search} onChange={event => { setSearch(event.target.value); setPage(0); }} /></div>
    {error && <ErrorState title={ar ? "تعذر تنفيذ العملية" : "Operation failed"} detail={error} />}
    {loading ? <LoadingState /> : visible.length ? <div className="currency-table-wrap inventory-table-wrap"><table className="currency-table"><thead><tr><th>{ar ? "رمز الصنف" : "Item code"}</th><th>{ar ? "الصنف" : "Item"}</th><th>{ar ? "الوحدة الأساسية" : "Base unit"}</th><th>{ar ? "الكمية المتاحة" : "Available qty"}</th><th>{ar ? "آخر سعر شراء" : "Last purchase"}</th><th>{ar ? "سعر البيع" : "Selling price"}</th><th>{ar ? "الحالة" : "Status"}</th><th>{ar ? "الإجراءات" : "Actions"}</th></tr></thead><tbody>{pageRows.map(item => <tr key={item.itemId}><td dir="ltr"><code>{item.itemCode}</code></td><td><strong>{ar ? item.nameAr : item.nameEn}</strong></td><td>{ar ? item.baseUnitAr ?? "—" : item.baseUnitEn ?? "—"}</td><td><strong>{format(item.quantity)}</strong></td><td>{item.lastPurchasePrice == null ? "—" : `${format(item.lastPurchasePrice)} SDG`}</td><td>{format(item.sellPrice)} SDG</td><td><StatusBadge tone={status(item)}>{item.quantity <= 0 ? (ar ? "نفد" : "Out of stock") : item.quantity <= item.minimumLevelForAlert ? (ar ? "منخفض" : "Low stock") : (ar ? "متوفر" : "In stock")}</StatusBadge></td><td><div className="inventory-row-actions"><IconButton label={ar ? "عرض الباتشات" : "View batches"} onClick={() => void openBatches(item)}><Icon name="view" size={17} /></IconButton><IconButton label={ar ? "طلب إتلاف" : "Request disposal"} onClick={() => void openBatches(item)}><Icon name="disable" size={17} /></IconButton></div></td></tr>)}</tbody></table><div className="table-footer"><span className="table-total">{ar ? "الإجمالي" : "Total"}&nbsp; {visible.length}</span><div className="table-pagination-controls"><label className="rows-per-page"><span>{ar ? "عدد الصفوف" : "Lines per page"}</span><Select value={String(pageSize)} onChange={event => { setPageSize(Number(event.target.value)); setPage(0); }}><option value="10">10</option><option value="15">15</option><option value="25">25</option><option value="50">50</option></Select></label><div className="pagination"><Button size="small" className="pagination-arrow" disabled={page === 0} onClick={() => setPage(current => Math.max(0, current - 1))}>‹</Button><span className="pagination-current">{page + 1}</span><span>…</span><span>{pageCount}</span><Button size="small" className="pagination-arrow" disabled={page + 1 >= pageCount} onClick={() => setPage(current => Math.min(pageCount - 1, current + 1))}>›</Button></div></div></div></div> : <EmptyState title={search ? (ar ? "لا توجد نتائج" : "No results") : (ar ? "لا توجد أصناف في المخزن" : "No inventory items")} detail={ar ? "ستظهر الكميات عند ترحيل فواتير الشراء." : "Quantities will appear when purchase invoices are posted."} />}
    <Modal open={Boolean(batchItem)} title={batchItem ? `${ar ? "باتشات الصنف" : "Item batches"} — ${ar ? batchItem.nameAr : batchItem.nameEn}` : ""} closeLabel={ar ? "إغلاق" : "Close"} onClose={() => setBatchItem(null)}>{batchLoading ? <LoadingState /> : <div className="currency-table-wrap inventory-batches-table"><table className="currency-table"><thead><tr><th>{ar ? "رقم الفاتورة" : "Invoice"}</th><th>{ar ? "تاريخ الشراء" : "Purchase date"}</th><th>{ar ? "الباركود" : "Barcode"}</th><th>{ar ? "تاريخ الانتهاء" : "Expiry"}</th><th>{ar ? "الكمية" : "Qty"}</th><th>{ar ? "المتاح" : "Available"}</th><th>{ar ? "رقم الباتش" : "Batch no."}</th><th>{ar ? "إتلاف" : "Dispose"}</th></tr></thead><tbody>{batches.map(batch => <tr key={batch.purchaseLineId}><td>{batch.invoiceNo}</td><td>{date(batch.purchaseDate)}</td><td>{batch.barcode || "—"}</td><td>{date(batch.expiryDate)}</td><td>{format(batch.quantity)}</td><td><strong>{format(batch.availableQuantity)}</strong></td><td>{batch.batchNo}</td><td><IconButton label={ar ? "طلب إتلاف هذا الباتش" : "Request disposal for this batch"} disabled={batch.availableQuantity <= 0} onClick={() => batchItem && setDisposalBatch({ item: batchItem, batch })}><Icon name="disable" size={17} /></IconButton></td></tr>)}</tbody></table></div>}</Modal>
    <Modal open={Boolean(disposalBatch)} title={ar ? "طلب إتلاف باتش" : "Request batch disposal"} description={ar ? "سيتم إنشاء طلب للموافقة قبل التأثير على المخزون والحسابات." : "A request will be created for approval before stock and accounts are affected."} closeLabel={ar ? "إغلاق" : "Close"} onClose={() => !disposalSaving && setDisposalBatch(null)} busy={disposalSaving} footer={<><Button variant="ghost" disabled={disposalSaving} onClick={() => setDisposalBatch(null)}>{ar ? "إلغاء" : "Cancel"}</Button><Button variant="danger" loading={disposalSaving} onClick={() => void submitDisposal()}>{ar ? "إرسال الطلب" : "Submit request"}</Button></>}><div className="settings-form"><FormField label={ar ? "الباتش" : "Batch"}><TextInput readOnly value={disposalBatch?.batch.batchNo ?? ""} /></FormField><FormField label={ar ? "الكمية" : "Quantity"} required><TextInput type="number" min="0.01" max={disposalBatch?.batch.availableQuantity} value={disposalQty} onChange={event => setDisposalQty(event.target.value)} /></FormField><FormField label={ar ? "سبب الإتلاف" : "Disposal reason"} required><textarea className="text-input" value={disposalReason} onChange={event => setDisposalReason(event.target.value)} maxLength={500} /></FormField></div></Modal>
  </div>;
}
