using ElitePos.LocalService.Models;
using ElitePos.LocalService.Security;
using ElitePos.LocalService.Services;
namespace ElitePos.LocalService.Endpoints;
public static class CurrencyEndpoints
{
    public static IEndpointRouteBuilder MapCurrencyEndpoints(this IEndpointRouteBuilder endpoints) { var group = endpoints.MapGroup("/api/currencies").RequireAuthorization(); var write = group.MapGroup("").RequirePermission(PermissionCodes.SettingsManage); var rates = group.MapGroup("").RequirePermission(PermissionCodes.ExchangeRatesEdit); group.MapGet("", async (bool? includeInactive, CurrencyService service, CancellationToken ct) => Results.Ok(await service.GetAsync(includeInactive == true, ct))); group.MapGet("/{id:int}/rates/history", async (int id, string? from, string? to, CurrencyService service, CancellationToken ct) => { try { if (!TryParseDate(from, out var fromDate) || !TryParseDate(to, out var toDate) || fromDate.HasValue && toDate.HasValue && fromDate > toDate) return Results.BadRequest(new { error = "The history date range is invalid." }); var fromInclusive = fromDate?.ToDateTime(TimeOnly.MinValue); var toExclusive = toDate?.AddDays(1).ToDateTime(TimeOnly.MinValue); return Results.Ok(await service.GetRateHistoryAsync(id, fromInclusive, toExclusive, ct)); } catch (CurrencyException ex) { return Results.Problem(ex.Message, statusCode: ex.StatusCode); } }); write.MapPost("", (CurrencyWriteRequest request, CurrencyService service, CancellationToken ct) => Save(null, request, service, ct)); write.MapPut("/{id:int}", (int id, CurrencyWriteRequest request, CurrencyService service, CancellationToken ct) => Save(id, request, service, ct)); write.MapPost("/{id:int}/activate", (int id, CurrencyService service, CancellationToken ct) => SetActive(id, true, service, ct)); write.MapPost("/{id:int}/deactivate", (int id, CurrencyService service, CancellationToken ct) => SetActive(id, false, service, ct)); rates.MapPut("/{id:int}/rate", (int id, CurrencyRateWriteRequest request, CurrencyService service, CancellationToken ct) => SetRate(id, request, service, ct)); rates.MapPut("/rates", async (CurrencyRateBatchRequest request, CurrencyService service, CancellationToken ct) => { try { return Results.Ok(new { changed = await service.SetRatesAsync(request, ct) }); } catch (CurrencyException ex) { return Results.Problem(ex.Message, statusCode: ex.StatusCode); } }); return endpoints; }
    private static bool TryParseDate(string? value, out DateOnly? date) { if (string.IsNullOrWhiteSpace(value)) { date = null; return true; } if (DateOnly.TryParseExact(value, "yyyy-MM-dd", out var parsed)) { date = parsed; return true; } date = null; return false; }
    private static async Task<IResult> SetActive(int id, bool active, CurrencyService service, CancellationToken ct) { try { return await service.SetActiveAsync(id, active, ct) ? Results.NoContent() : Results.NotFound(); } catch (CurrencyException ex) { return Results.Problem(ex.Message, statusCode: ex.StatusCode); } }
    private static async Task<IResult> SetRate(int id, CurrencyRateWriteRequest request, CurrencyService service, CancellationToken ct) { try { return Results.Ok(await service.SetRateAsync(id, request, ct)); } catch (CurrencyException ex) { return Results.Problem(ex.Message, statusCode: ex.StatusCode); } }
    private static async Task<IResult> Save(int? id, CurrencyWriteRequest request, CurrencyService service, CancellationToken ct) { try { var result = await service.SaveAsync(id, request, ct); return id.HasValue ? Results.Ok(result) : Results.Created("/api/currencies", result); } catch (CurrencyException ex) { return Results.Problem(ex.Message, statusCode: ex.StatusCode); } catch (Exception ex) when (ex.ToString().Contains("2601", StringComparison.Ordinal) || ex.ToString().Contains("2627", StringComparison.Ordinal)) { return Results.Conflict(new { error = "Currency code or primary currency conflicts with an existing record." }); } }
}
