import { useCallback, useState } from 'react'
import { Button, ErrorState, FormField, IconButton, Modal, StatusBadge, SwitchInput, TextInput } from '../../components/shared'
import { useLoadEffect } from '../../components/useLoadEffect'
import { DataTable, type TableColumn } from '../../components/DataTable'
import { Icon } from '../../components/icons'
import { PageHeader, type Locale } from '../../layouts/AppLayout'
type Bank={bankId:number;bankCode:string;nameAr:string;nameEn:string;isActive:boolean;sortOrder:number}
export function BanksPage({locale,onBack}:{locale:Locale;onBack:()=>void}) {
 const ar=locale==='ar'; const [rows,setRows]=useState<Bank[]>([]); const [includeInactive,setIncludeInactive]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [modal,setModal]=useState(false); const [editing,setEditing]=useState<Bank|null>(null); const [draft,setDraft]=useState({nameAr:'',nameEn:'',isActive:true}); const [saving,setSaving]=useState(false)
 const load = useCallback(async () => {setLoading(true);setError('');try{const r=await fetch(`/api/banks${includeInactive?'?includeInactive=true':''}`);if(!r.ok)throw new Error(ar?'تعذر تحميل البنوك.':'Could not load banks.');setRows(await r.json())}catch(e){setError(e instanceof Error?e.message:'Request failed')}finally{setLoading(false)}}, [includeInactive, ar])
 useLoadEffect(load)
 function open(item?:Bank){setEditing(item??null);setDraft(item?{nameAr:item.nameAr,nameEn:item.nameEn,isActive:item.isActive}:{nameAr:'',nameEn:'',isActive:true});setModal(true)}
 async function save(){if(!draft.nameAr.trim()||!draft.nameEn.trim()){setError(ar?'أدخل الاسم بالعربية والإنجليزية.':'Enter both Arabic and English names.');return}setSaving(true);try{const r=await fetch(editing?`/api/banks/${editing.bankId}`:'/api/banks',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});if(!r.ok)throw new Error(await r.text());setModal(false);await load()}catch(e){setError(e instanceof Error?e.message:'Could not save bank.')}finally{setSaving(false)}}
 const columns:Array<TableColumn<Bank>>=[{key:'bankCode',title:ar?'الرمز':'Code',value:x=>x.bankCode,render:x=><span className="doc-no">{x.bankCode}</span>},{key:'nameAr',title:ar?'الاسم بالعربية':'Arabic name',value:x=>x.nameAr,render:x=><span dir="rtl">{x.nameAr}</span>},{key:'nameEn',title:ar?'الاسم بالإنجليزية':'English name',value:x=>x.nameEn},{key:'isActive',title:ar?'الحالة':'Status',value:x=>x.isActive,searchable:false,render:x=><StatusBadge tone={x.isActive?'success':'danger'}>{x.isActive?(ar?'نشط':'Active'):(ar?'غير نشط':'Inactive')}</StatusBadge>}]
 return <div className="settings-page" dir={ar?'rtl':'ltr'}><button type="button" className="locations-back" onClick={onBack}>{ar?'‹ الإعدادات':'‹ Settings'}</button><PageHeader title={ar?'البنوك':'Banks'} description={ar?'إدارة البنوك المستخدمة للحسابات البنكية.':'Manage banks used by bank treasures.'} actions={<Button variant="primary" onClick={()=>open()}><Icon name="plus" size={18} />{ar?'إضافة بنك':'Add bank'}</Button>}/>{error&&<ErrorState title={ar?'تعذر تنفيذ العملية':'Request failed'} detail={error}/>}<DataTable locale={locale} columns={columns} rows={rows} rowKey={x=>x.bankId} loading={loading} density="compact" pageSize={15} searchLabel={ar?'بحث':'Search banks'} searchPlaceholder={ar?'ابحث بالرمز أو الاسم':'Search code or name'} toolbarEnd={<SwitchInput label={ar?'عرض غير النشط':'Show inactive'} checked={includeInactive} onChange={e=>setIncludeInactive(e.target.checked)}/>} rowActions={x=><IconButton label={ar?'تعديل':'Edit'} onClick={()=>open(x)}><Icon name="edit" size={18}/></IconButton>} emptyTitle={ar?'لا توجد بنوك':'No banks'} emptyDetail={ar?'أضف أول بنك للبدء.':'Add the first bank to begin.'}/><Modal open={modal} title={editing?(ar?'تعديل بنك':'Edit bank'):(ar?'إضافة بنك':'Add bank')} closeLabel={ar?'إغلاق':'Close'} onClose={()=>!saving&&setModal(false)} busy={saving} footer={<><Button variant="ghost" onClick={()=>setModal(false)}>{ar?'إلغاء':'Cancel'}</Button><Button variant="primary" loading={saving} onClick={()=>void save()}>{ar?'حفظ':'Save'}</Button></>}><div className="settings-form">{editing&&<div className="setting-code-meta"><span>{ar?'رمز النظام':'System code'}</span><code>{editing.bankCode}</code></div>}<FormField label={ar?'اسم البنك بالعربية':'Arabic name'} required><TextInput dir="rtl" value={draft.nameAr} onChange={e=>setDraft({...draft,nameAr:e.target.value})}/></FormField><FormField label={ar?'اسم البنك بالإنجليزية':'English name'} required><TextInput value={draft.nameEn} onChange={e=>setDraft({...draft,nameEn:e.target.value})}/></FormField><SwitchInput label={ar?'نشط':'Active'} checked={draft.isActive} onChange={e=>setDraft({...draft,isActive:e.target.checked})}/></div></Modal></div>
}
