import { useEffect, useMemo, useState } from 'react'
import { Button, DateInput, EmptyState, ErrorState, FormField, LoadingState, Modal, SearchInput, Select, TableFooter, TextInput } from '../../components/shared'
import { usePagination } from '../../components/usePagination'
import { Icon } from '../../components/icons'
import { PageHeader, type Locale } from '../../layouts/AppLayout'

type Expense = { moveNo: number; expenseNo: string; expenseDate: string; expenseAccountId: string; expenseNameEn: string; expenseNameAr: string; treasuryId: number; treasuryName: string; currencyId: number; currencyCode: string; currencySymbol: string; amount: number; description: string | null }
type Treasury = { treasuryId: number; nameAr: string; nameEn: string; currencyId: number; currencySymbol: string; isActive: boolean }
type Account = { accountId: number; accountCode: string; nameAr: string; nameEn: string; accountType: string; isActive: boolean }
const today = () => new Date().toISOString().slice(0, 10)
const formatAmount = (value: number | string) => (Number(value) || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })

export function ExpensesPage({ locale }: { locale: Locale }) {
  const ar = locale === 'ar'; const [rows, setRows] = useState<Expense[]>([]); const [treasuries, setTreasuries] = useState<Treasury[]>([]); const [accounts, setAccounts] = useState<Account[]>([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [modal, setModal] = useState(false); const [error, setError] = useState('')
  const [draft, setDraft] = useState({ expenseAccountId: '', treasuryId: '', amount: '', expenseDate: today(), description: '' })
  async function load() { setLoading(true); setError(''); try { const [expenseResponse, treasuryResponse, accountResponse] = await Promise.all([fetch('/api/expenses'), fetch('/api/treasuries'), fetch('/api/accounts/chart')]); if (!expenseResponse.ok || !treasuryResponse.ok || !accountResponse.ok) throw new Error(ar ? 'تعذر تحميل بيانات المنصرفات.' : 'Could not load expense data.'); setRows(await expenseResponse.json()); setTreasuries(await treasuryResponse.json()); setAccounts(await accountResponse.json()) } catch (reason) { setError(reason instanceof Error ? reason.message : (ar ? 'تعذر تنفيذ العملية.' : 'Request failed.')) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const expenseAccounts = accounts.filter(item => item.accountType === 'EXPENSE' && item.isActive)
  const visible = useMemo(() => { const q = search.trim().toLocaleLowerCase(); return rows.filter(item => !q || [item.expenseNo, item.expenseAccountId, item.expenseNameAr, item.expenseNameEn, item.treasuryName, item.description ?? ''].some(value => value.toLocaleLowerCase().includes(q))) }, [rows, search])
  function open() { const treasury = treasuries.find(item => item.isActive); setDraft({ expenseAccountId: expenseAccounts[0]?.accountCode ?? '', treasuryId: treasury?.treasuryId.toString() ?? '', amount: '', expenseDate: today(), description: '' }); setError(''); setModal(true) }
  async function save() { if (!draft.expenseAccountId || !draft.treasuryId || Number(draft.amount) <= 0) { setError(ar ? 'اختر حساب المصروف والخزينة وأدخل مبلغاً صحيحاً.' : 'Choose an expense account and treasury and enter a valid amount.'); return } setSaving(true); setError(''); try { const response = await fetch('/api/expenses', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ expenseAccountId: draft.expenseAccountId, treasuryId: Number(draft.treasuryId), amount: Number(draft.amount), expenseDate: draft.expenseDate, description: draft.description.trim() || null }) }); if (!response.ok) throw new Error(await response.text()); setModal(false); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : (ar ? 'تعذر حفظ المنصرف.' : 'Could not save expense.')) } finally { setSaving(false) } }
  const visiblePage = usePagination(visible)
  return <div className="receipts-page expenses-page" dir={ar ? 'rtl' : 'ltr'}><PageHeader eyebrow={ar ? 'المعاملات المالية' : 'FINANCE'} title={ar ? 'المنصرفات' : 'Expenses'} description={ar ? 'تسجيل ومراجعة المبالغ المصروفة من الخزائن.' : 'Record and review amounts paid from treasuries.'} actions={<Button variant="primary" onClick={open}>＋ {ar ? 'إضافة منصرف' : 'Add expense'}</Button>} /><section className="receipts-toolbar"><SearchInput aria-label={ar ? 'بحث في المنصرفات' : 'Search expenses'} placeholder={ar ? 'ابحث برقم المنصرف أو الحساب أو البيان' : 'Search expense, account or description'} value={search} onChange={event => setSearch(event.target.value)} /></section>{error && !modal && <ErrorState title={ar ? 'تعذر تنفيذ العملية' : 'Request failed'} detail={error} />}{loading ? <LoadingState label={ar ? 'جارٍ تحميل المنصرفات…' : 'Loading expenses…'} /> : visible.length === 0 ? <EmptyState title={ar ? 'لا توجد منصرفات' : 'No expenses yet'} detail={ar ? 'أضف أول منصرف للبدء.' : 'Add an expense to begin.'} /> : <div className="receipts-table-wrap"><table className="receipts-table"><thead><tr><th>{ar ? 'رقم المنصرف' : 'Expense no.'}</th><th>{ar ? 'التاريخ' : 'Date'}</th><th>{ar ? 'حساب المصروف' : 'Expense account'}</th><th>{ar ? 'الخزينة' : 'Treasury'}</th><th>{ar ? 'المبلغ' : 'Amount'}</th><th>{ar ? 'البيان' : 'Description'}</th></tr></thead><tbody>{visiblePage.rows.map(item => <tr key={item.moveNo}><td><code>{item.expenseNo}</code></td><td>{item.expenseDate.slice(0, 10)}</td><td>{ar ? item.expenseNameAr : item.expenseNameEn} <small>({item.expenseAccountId})</small></td><td>{item.treasuryName}</td><td className="numeric-cell">{formatAmount(item.amount)} <small>{item.currencySymbol}</small></td><td>{item.description ?? '—'}</td></tr>)}</tbody></table><TableFooter total={visible.length} locale={locale} pager={visiblePage.pager} /></div>}
    <Modal open={modal} title={ar ? 'إضافة منصرف' : 'Add expense'} titleIcon="currency" description={ar ? 'يتم تسجيل قيد مدين على حساب المصروف ودائن على الخزينة.' : 'This records a debit to the expense account and a credit to the treasury.'} closeLabel={ar ? 'إغلاق' : 'Close'} busy={saving} onClose={() => !saving && setModal(false)} footer={<><Button variant="ghost" disabled={saving} onClick={() => setModal(false)}>{ar ? 'إلغاء' : 'Cancel'}</Button><Button variant="primary" loading={saving} onClick={() => void save()}>{ar ? 'حفظ المنصرف' : 'Save expense'}</Button></>}><div className="receipt-form"><div className="receipt-form-grid"><FormField label={ar ? 'التاريخ' : 'Date'} required><DateInput value={draft.expenseDate} onChange={event => setDraft({ ...draft, expenseDate: event.target.value })} /></FormField><FormField label={ar ? 'حساب المصروف' : 'Expense account'} required><Select value={draft.expenseAccountId} onChange={event => setDraft({ ...draft, expenseAccountId: event.target.value })}><option value="">{ar ? 'اختر حساب المصروف' : 'Choose expense account'}</option>{expenseAccounts.map(item => <option key={item.accountCode} value={item.accountCode}>{item.accountCode} — {ar ? item.nameAr : item.nameEn}</option>)}</Select></FormField><FormField label={ar ? 'الخزينة' : 'Treasury'} required><Select value={draft.treasuryId} onChange={event => setDraft({ ...draft, treasuryId: event.target.value })}><option value="">{ar ? 'اختر الخزينة' : 'Choose treasury'}</option>{treasuries.filter(item => item.isActive).map(item => <option key={item.treasuryId} value={item.treasuryId}>{ar ? item.nameAr : item.nameEn} · {item.currencySymbol}</option>)}</Select></FormField><FormField label={ar ? 'المبلغ' : 'Amount'} required><TextInput dir="ltr" type="number" min="0.01" step="0.01" value={draft.amount} onChange={event => setDraft({ ...draft, amount: event.target.value })} placeholder="0.00" /></FormField><FormField label={ar ? 'البيان' : 'Description'}><textarea className="text-input receipt-description" value={draft.description} maxLength={250} onChange={event => setDraft({ ...draft, description: event.target.value })} rows={3} /></FormField></div>{error && <div className="receipt-form-error" role="alert">{error}</div>}<p className="receipt-account-note"><Icon name="info" size={16} />{ar ? 'لن يتم استخدام شريك في المنصرف؛ سيتم ترحيله مباشرة بين حساب المصروف والخزينة.' : 'Expenses do not use a partner; they post directly between the expense account and treasury.'}</p></div></Modal>
  </div>
}
