import { useState, type FormEvent } from 'react'
import { Button, TextInput } from '../../components/shared'
import type { Locale } from '../../layouts/AppLayout'

export function ChangePasswordPage({ locale, onChanged }: { locale: Locale; onChanged: () => void }) {
  const ar = locale === 'ar'; const [current, setCurrent] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); if (!current) return setError(ar ? 'أدخل كلمة المرور الحالية.' : 'Enter your current password.'); if (password.length < 8) return setError(ar ? 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل.' : 'The new password must be at least 8 characters.'); if (!password) return setError(ar ? 'أدخل كلمة المرور الجديدة.' : 'Enter a new password.'); if (password !== confirm) return setError(ar ? 'كلمتا المرور غير متطابقتين.' : 'Passwords do not match.'); setBusy(true); setError(''); try { const response = await fetch('/api/auth/change-password', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ currentPassword: current, newPassword: password }) }); if (!response.ok) { const problem = await response.json().catch(() => null) as { detail?: string } | null; throw new Error(ar ? 'تعذر تغيير كلمة المرور. تحقق من كلمة المرور الحالية.' : problem?.detail ?? 'Could not change password.') } onChanged() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Request failed.') } finally { setBusy(false) } }
  return <main className="login-screen" dir={ar ? 'rtl' : 'ltr'}><section className="login-panel"><div className="login-brand"><span className="login-mark">E</span><div><strong>Elite POS</strong><small>{ar ? 'نظام نقاط البيع' : 'Point of sale'}</small></div></div><div className="login-heading"><h1>{ar ? 'غيّر كلمة المرور' : 'Change your password'}</h1><p>{ar ? 'يجب تغيير كلمة المرور المؤقتة قبل المتابعة.' : 'You must change your temporary password before continuing.'}</p></div><form className="login-form" onSubmit={submit}><label>{ar ? 'كلمة المرور الحالية' : 'Current password'}<span className="login-input"><TextInput autoFocus type="password" value={current} onChange={event => setCurrent(event.target.value)} /></span></label><label>{ar ? 'كلمة المرور الجديدة' : 'New password'}<span className="login-input"><TextInput type="password" value={password} onChange={event => setPassword(event.target.value)} /></span></label><label>{ar ? 'تأكيد كلمة المرور' : 'Confirm password'}<span className="login-input"><TextInput type="password" value={confirm} onChange={event => setConfirm(event.target.value)} /></span></label>{error && <p className="login-error" role="alert">{error}</p>}<Button type="submit" variant="primary" loading={busy} className="login-submit">{ar ? 'حفظ كلمة المرور' : 'Save password'}</Button></form></section></main>
}

