import { useEffect, useState, type ReactNode } from 'react'
import { Button, FormField, Select, TextInput, ErrorState } from '../../components/shared'
import { Icon } from '../../components/icons'
import { PageHeader, type Locale } from '../../layouts/AppLayout'

type Currency = { currencyId: number; currencyCode: string; currencyNameEn: string; currencyNameAr: string; symbol: string; isPrimary: boolean; exchangeRate: number | null; isActive: boolean; flagBase64: string | null }
type Treasury = { treasuryId: number; nameAr: string; nameEn: string; currencyId: number; currencySymbol: string; currencyCode: string; isActive: boolean; flagBase64?: string | null }
const amount = (value: string) => Number(value) || 0
const formatAmount = (value: number) => value.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })

function TreasuryCard({ treasury, balance, loading, locale, direction, children }: { treasury?: Treasury; balance: number | null; loading: boolean; locale: Locale; direction: 'source' | 'destination'; children: ReactNode }) {
  const ar = locale === 'ar'; const source = direction === 'source'
  return <article className={`treasury-transfer-party treasury-transfer-party-${direction}`}>
    <div className="treasury-transfer-party-icon"><Icon name={source ? 'wallet' : 'bank'} size={27} /></div>
    <div className="treasury-transfer-party-content"><div className="treasury-transfer-party-heading"><strong>{ar ? (source ? 'من الخزنة' : 'إلى الخزنة') : (source ? 'From treasury' : 'To treasury')} <span className="required-mark">*</span></strong></div><div className="treasury-transfer-party-controls">{children}</div><div className="treasury-transfer-party-balance"><span>{ar ? 'الرصيد المتاح' : 'Available balance'}</span><strong>{loading ? '…' : `${formatAmount(balance ?? 0)} ${treasury?.currencySymbol ?? ''}`}</strong></div></div>
  </article>
}

function TreasurySelect({ value, onChange, treasuries, locale, placeholder }: { value: string; onChange: (value: string) => void; treasuries: Treasury[]; locale: Locale; placeholder: string }) {
  const ar = locale === 'ar'
  return <Select value={value} onChange={event => onChange(event.target.value)}>
    <option value="">{placeholder}</option>
    {treasuries.map(item => <option key={item.treasuryId} value={item.treasuryId}>{ar ? item.nameAr : item.nameEn} · {item.currencySymbol}</option>)}
  </Select>
}

export function TreasuryTransferPage({ locale }: { locale: Locale }) {
  const ar = locale === 'ar'
  const [treasuries, setTreasuries] = useState<Treasury[]>([]); const [currencies, setCurrencies] = useState<Currency[]>([]); const [sourceId, setSourceId] = useState(''); const [destinationId, setDestinationId] = useState('')
  const [sourceAmount, setSourceAmount] = useState(''); const [destinationAmount, setDestinationAmount] = useState(''); const [lastEditedAmount, setLastEditedAmount] = useState<'source' | 'destination'>('source'); const [exchangeRate, setExchangeRate] = useState('1'); const [reverseRate, setReverseRate] = useState(false); const [rateDraft, setRateDraft] = useState('1'); const [description, setDescription] = useState('')
  const [sourceBalance, setSourceBalance] = useState<number | null>(null); const [destinationBalance, setDestinationBalance] = useState<number | null>(null); const [balanceLoading, setBalanceLoading] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [saved, setSaved] = useState(false)
  useEffect(() => { Promise.all([fetch('/api/treasuries'), fetch('/api/currencies')]).then(async ([treasuryResponse, currencyResponse]) => { if (!treasuryResponse.ok || !currencyResponse.ok) throw new Error('load'); const [items, currencyItems] = await Promise.all([treasuryResponse.json() as Promise<Treasury[]>, currencyResponse.json() as Promise<Currency[]>]); setCurrencies(currencyItems); const activeCurrencies = new Map(currencyItems.map(item => [item.currencyId, item])); setTreasuries(items.filter(item => item.isActive).map(item => ({ ...item, flagBase64: activeCurrencies.get(item.currencyId)?.flagBase64 ?? null }))) }).catch(() => setError(ar ? 'تعذر تحميل الخزن والعملات.' : 'Could not load treasuries and currencies.')) }, [ar])
  const source = treasuries.find(item => item.treasuryId.toString() === sourceId); const destination = treasuries.find(item => item.treasuryId.toString() === destinationId); const sameCurrency = Boolean(source && destination && source.currencyId === destination.currencyId)
  const sourceCurrencySymbol = source?.currencySymbol ?? ''; const destinationCurrencySymbol = destination?.currencySymbol ?? ''
  const sourceCurrency = currencies.find(item => item.currencyId === source?.currencyId); const destinationCurrency = currencies.find(item => item.currencyId === destination?.currencyId)
  const currencyRate = (currencyId: number | undefined) => { const currency = currencies.find(item => item.currencyId === currencyId); return currency?.isPrimary ? 1 : currency?.exchangeRate ?? null }
  const pairRate = (sourceCurrencyId: number | undefined, destinationCurrencyId: number | undefined) => { const sourceRate = currencyRate(sourceCurrencyId); const destinationRate = currencyRate(destinationCurrencyId); return sourceRate && destinationRate ? destinationRate / sourceRate : null }
  useEffect(() => { if (!sourceId) { setSourceBalance(null); return }; let active = true; setBalanceLoading(true); fetch(`/api/transactions/treasury/${sourceId}`).then(response => response.ok ? response.json() as Promise<{ rows: Array<{ foreignDebit: number; foreignCredit: number }> }> : Promise.reject(new Error('balance'))).then(statement => { if (active) setSourceBalance(statement.rows.reduce((total, row) => total + row.foreignDebit - row.foreignCredit, 0)) }).catch(() => { if (active) setSourceBalance(null) }).finally(() => { if (active) setBalanceLoading(false) }); return () => { active = false } }, [sourceId])
  useEffect(() => { if (!destinationId) { setDestinationBalance(null); return }; let active = true; fetch(`/api/transactions/treasury/${destinationId}`).then(response => response.ok ? response.json() as Promise<{ rows: Array<{ foreignDebit: number; foreignCredit: number }> }> : Promise.reject(new Error('balance'))).then(statement => { if (active) setDestinationBalance(statement.rows.reduce((total, row) => total + row.foreignDebit - row.foreignCredit, 0)) }).catch(() => { if (active) setDestinationBalance(null) }); return () => { active = false } }, [destinationId])
  useEffect(() => { if (!source || !destination) return; const rate = sameCurrency ? 1 : pairRate(source.currencyId, destination.currencyId); if (rate) { const next = String(Number(rate.toFixed(8))); const preferOtherCurrencyAsOne = Boolean(!sameCurrency && sourceCurrency?.isPrimary && !destinationCurrency?.isPrimary); setReverseRate(preferOtherCurrencyAsOne); setExchangeRate(next); setRateDraft(preferOtherCurrencyAsOne ? next : (1 / Number(next)).toString()) } }, [source?.currencyId, destination?.currencyId, sameCurrency, currencies])
  useEffect(() => { const rate = amount(exchangeRate); if (!rate) return; if (sameCurrency) { setDestinationAmount(sourceAmount); return }; if (lastEditedAmount === 'source' && sourceAmount) setDestinationAmount((amount(sourceAmount) / rate).toFixed(4).replace(/\.?(0+)$/, '')); else if (lastEditedAmount === 'destination' && destinationAmount) setSourceAmount((amount(destinationAmount) * rate).toFixed(4).replace(/\.?(0+)$/, '')) }, [sameCurrency, sourceAmount, destinationAmount, exchangeRate, lastEditedAmount])
  const exceedsBalance = sourceBalance !== null && amount(sourceAmount) > sourceBalance + 0.0001; const canSave = Boolean(source && destination && amount(sourceAmount) > 0 && amount(destinationAmount) > 0 && amount(exchangeRate) > 0 && source.treasuryId !== destination.treasuryId && !exceedsBalance)
  const swapTreasuries = () => { setSourceId(destinationId); setDestinationId(sourceId); setSourceAmount(destinationAmount); setDestinationAmount(sourceAmount) }
  async function save() { if (!source || !destination || source.treasuryId === destination.treasuryId) { setError(ar ? 'اختر خزنتين مختلفتين.' : 'Choose two different treasuries.'); return }; if (exceedsBalance) { setError(ar ? 'مبلغ التحويل أكبر من الرصيد المتاح في الخزنة المصدر.' : 'The transfer amount exceeds the available source balance.'); return }; if (!canSave) { setError(ar ? 'أدخل مبالغ صحيحة للتحويل.' : 'Enter valid transfer amounts.'); return }; setSaving(true); setError(''); setSaved(false); try { const response = await fetch('/api/treasury-transfers', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ sourceTreasuryId: source.treasuryId, destinationTreasuryId: destination.treasuryId, sourceAmount: amount(sourceAmount), destinationAmount: amount(destinationAmount), exchangeRate: amount(exchangeRate), description: description.trim() || null }) }); if (!response.ok) throw new Error(await response.text()); setSaved(true); setSourceAmount(''); setDestinationAmount(''); setDescription('') } catch (reason) { setError(reason instanceof Error ? reason.message : (ar ? 'تعذر حفظ التحويل.' : 'Could not save transfer.')) } finally { setSaving(false) } }

  return <div className="treasury-transfer-page" dir={ar ? 'rtl' : 'ltr'}>
    <PageHeader eyebrow={ar ? 'الحسابات' : 'ACCOUNTS'} title={ar ? 'تحويل بين الخزن' : 'Treasury transfer'} description={ar ? 'نقل الأموال بين الخزن مع تحويل العملة عند اختلافها.' : 'Move funds between treasuries with exchange conversion when currencies differ.'} />
    <section className="treasury-transfer-workspace">
      <div className="treasury-transfer-layout">
        <TreasuryCard treasury={source} balance={sourceBalance} loading={balanceLoading} locale={locale} direction="source"><TreasurySelect value={sourceId} onChange={value => setSourceId(value)} treasuries={treasuries} locale={locale} placeholder={ar ? 'اختر الخزنة' : 'Choose treasury'} /><div className="treasury-transfer-input-block"><FormField label={ar ? 'المبلغ المحول' : 'Amount to transfer'} required><div className="treasury-transfer-amount-input"><TextInput type="number" min="0" step="0.01" value={sourceAmount} onChange={event => { setLastEditedAmount('source'); setSourceAmount(event.target.value) }} placeholder="0.00" /><span>{sourceCurrencySymbol || '—'}</span></div></FormField><small>{ar ? 'المتاح' : 'Available'}: {sourceBalance === null ? '—' : `${formatAmount(sourceBalance)} ${sourceCurrencySymbol}`}</small></div></TreasuryCard>
        <span className="treasury-transfer-direction-arrow" aria-hidden="true"><Icon name="arrow-right" size={22} /></span>
        <div className="treasury-transfer-center"><button className="treasury-transfer-swap" type="button" onClick={swapTreasuries} aria-label={ar ? 'تبديل الخزن' : 'Swap treasuries'}><Icon name="swap" size={27} /></button><article className="treasury-transfer-exchange"><div className="treasury-transfer-exchange-heading"><span>{ar ? 'سعر التحويل' : 'Exchange rate'} <span className="required-mark">*</span></span><button type="button" className={`treasury-transfer-rate-toggle${reverseRate ? ' is-active' : ''}`} onClick={() => setReverseRate(value => { const next = !value; setRateDraft(next ? exchangeRate : (amount(exchangeRate) ? (1 / amount(exchangeRate)).toString() : '')); return next })}>{ar ? 'عكس السعر' : 'Reverse rate'}</button></div><div className="treasury-transfer-rate-pair"><div className="treasury-transfer-rate-result"><strong>1.00</strong><span>{(reverseRate ? destinationCurrencySymbol : sourceCurrencySymbol) || '—'}</span></div><span className="treasury-transfer-equals">=</span><div className="treasury-transfer-rate-input"><TextInput dir="ltr" type="number" min="0" step="0.0001" value={sameCurrency ? '1.00' : rateDraft} disabled={sameCurrency} onChange={event => { const raw = event.target.value; setRateDraft(raw); const next = Number(raw); setExchangeRate(next > 0 ? String(reverseRate ? next : 1 / next) : '') }} /><span>{(reverseRate ? sourceCurrencySymbol : destinationCurrencySymbol) || '—'}</span></div></div><div className="treasury-transfer-rate-note"><Icon name="info" size={20} /><div><strong>1 {(reverseRate ? destinationCurrencySymbol : sourceCurrencySymbol) || '—'} = {sameCurrency ? '1.00' : rateDraft || '—'} {(reverseRate ? sourceCurrencySymbol : destinationCurrencySymbol) || '—'}</strong><small>{ar ? `ستستلم الخزنة الوجهة ${formatAmount(amount(destinationAmount))} ${destinationCurrencySymbol}.` : `The destination treasury will receive ${formatAmount(amount(destinationAmount))} ${destinationCurrencySymbol}.`}</small></div></div></article></div>
        <span className="treasury-transfer-direction-arrow" aria-hidden="true"><Icon name="arrow-right" size={22} /></span>
        <TreasuryCard treasury={destination} balance={destinationBalance} loading={false} locale={locale} direction="destination"><TreasurySelect value={destinationId} onChange={value => setDestinationId(value)} treasuries={treasuries.filter(item => item.treasuryId.toString() !== sourceId)} locale={locale} placeholder={ar ? 'اختر الخزنة' : 'Choose treasury'} /><div className="treasury-transfer-input-block"><FormField label={ar ? 'المبلغ المستلم' : 'Amount to receive'}><div className="treasury-transfer-amount-input"><TextInput type="number" min="0" step="0.01" value={destinationAmount} disabled={sameCurrency} onChange={event => { setLastEditedAmount('destination'); setDestinationAmount(event.target.value) }} placeholder="0.00" /><span>{destinationCurrencySymbol || '—'}</span></div></FormField><small>{ar ? 'الرصيد بعد التحويل' : 'Available after transfer'}: {destinationBalance === null ? '—' : `${formatAmount(destinationBalance + amount(destinationAmount))} ${destinationCurrencySymbol}`}</small></div></TreasuryCard>
      </div>
      <div className="treasury-transfer-description"><div className="treasury-transfer-description-icon"><Icon name="document" size={24} /></div><FormField label={ar ? 'البيان' : 'Description'}><textarea className="text-input treasury-transfer-textarea" value={description} maxLength={200} onChange={event => setDescription(event.target.value)} placeholder={ar ? 'مثال: تغذية خزنة البنك أو ترحيل الإغلاق' : 'e.g. Fund bank treasury, shift closing, etc.'} /><small>{description.length}/200</small></FormField></div>
      {exceedsBalance && <div className="treasury-transfer-warning">{ar ? 'مبلغ التحويل أكبر من الرصيد المتاح في الخزنة المصدر.' : 'The transfer amount exceeds the available source balance.'}</div>}{error && <ErrorState title={ar ? 'تعذر تنفيذ التحويل' : 'Transfer failed'} detail={error} />}{saved && <div className="profile-save-message">{ar ? 'تم تسجيل التحويل بنجاح.' : 'Transfer recorded successfully.'}</div>}
      <div className="treasury-transfer-footer"><button className="treasury-transfer-recent" type="button"><Icon name="history" size={22} />{ar ? 'التحويلات الأخيرة' : 'Recent transfers'}</button><div><Button variant="outline" onClick={() => { setSourceAmount(''); setDestinationAmount(''); setDescription(''); setError('') }}>{ar ? 'إلغاء' : 'Cancel'}</Button><Button variant="primary" loading={saving} disabled={!canSave || saving} onClick={() => void save()}><Icon name="swap" size={18} />{ar ? `تحويل ${formatAmount(amount(sourceAmount))} ${sourceCurrencySymbol}` : `Transfer ${formatAmount(amount(sourceAmount))} ${sourceCurrencySymbol}`}</Button></div></div>
    </section>
  </div>
}





