import { useEffect, useMemo, useState, type KeyboardEvent } from 'react'
import { Button, Card, FormField, LoadingState, SearchInput, Select, TextInput } from '../../components/shared'
import { PageHeader, type Locale } from '../../layouts/AppLayout'

type Item = { itemId: number; itemCode: string; nameAr: string; nameEn: string; sellPrice: number }
type Treasury = { treasuryId: number; nameAr: string; nameEn: string; currencyId: number; currencySymbol: string; isActive: boolean }
type Currency = { currencyId: number; symbol: string; isPrimary: boolean }
type Partner = { partnerId: number; partnerName: string; status: string; partnerTypeCode?: string }
type Line = { itemId: string; quantity: string; unitPrice: string }
type SaleRow = { saleNo: string; saleDate: string; total: number; currencySymbol: string; customerName?: string | null }

export function SalesPage({ locale, branchId, userId }: { locale: Locale; branchId: number; userId: number }) {
  const ar = locale === 'ar'
  const [newSale, setNewSale] = useState(false); const [items, setItems] = useState<Item[]>([]); const [treasuries, setTreasuries] = useState<Treasury[]>([]); const [partners, setPartners] = useState<Partner[]>([]); const [primaryCurrency, setPrimaryCurrency] = useState<Currency | null>(null); const [rows, setRows] = useState<SaleRow[]>([]); const [treasuryId, setTreasuryId] = useState(''); const [saleType, setSaleType] = useState<'DIRECT' | 'CUSTOMER'>('DIRECT'); const [customerId, setCustomerId] = useState(''); const [lines, setLines] = useState<Line[]>([{ itemId: '', quantity: '1', unitPrice: '0' }]); const [discount, setDiscount] = useState('0'); const [itemSearch, setItemSearch] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('')
  async function load() { const responses = await Promise.all([fetch('/api/items'), fetch('/api/treasuries'), fetch('/api/currencies'), fetch('/api/partners/options'), fetch('/api/sales')]); if (responses.some(response => !response.ok)) throw new Error('load'); const currencies = await responses[2].json() as Currency[]; const primary = currencies.find(currency => currency.isPrimary) ?? null; setPrimaryCurrency(primary); setItems(await responses[0].json()); const allTreasuries = await responses[1].json() as Treasury[]; setTreasuries(allTreasuries.filter(treasury => treasury.isActive && treasury.currencyId === primary?.currencyId)); setPartners((await responses[3].json() as Partner[]).filter(partner => partner.status === 'ACTIVE')); setRows(await responses[4].json()) }
  useEffect(() => { load().catch(() => setMessage(ar ? 'تعذر تحميل شاشة المبيعات.' : 'Could not load sales.')).finally(() => setLoading(false)) }, [ar])
  const subtotal = useMemo(() => lines.reduce((sum, line) => sum + (Number(line.quantity) || 0) * (Number(line.unitPrice) || 0), 0), [lines]); const total = Math.max(0, subtotal - (Number(discount) || 0))
  function resetSale() { setTreasuryId(''); setSaleType('DIRECT'); setCustomerId(''); setLines([{ itemId: '', quantity: '1', unitPrice: '0' }]); setDiscount('0'); setItemSearch(''); setMessage('') }
  function selectItem(index: number, value: string) { const item = items.find(candidate => String(candidate.itemId) === value); setLines(current => current.map((line, rowIndex) => rowIndex === index ? { ...line, itemId: value, unitPrice: item?.sellPrice?.toString() ?? '0' } : line)) }
  function handleItemSearchKeyDown(event: KeyboardEvent<HTMLInputElement>) {
    if (event.key !== 'Enter') return
    event.preventDefault()
    const barcode = itemSearch.trim().toLocaleLowerCase()
    if (!barcode) return
    const item = items.find(candidate => candidate.itemCode.trim().toLocaleLowerCase() === barcode)
    if (!item) return
    setLines(current => {
      const existingIndex = current.findIndex(line => line.itemId === String(item.itemId))
      if (existingIndex >= 0) return current.map((line, index) => index === existingIndex ? { ...line, quantity: String((Number(line.quantity) || 0) + 1) } : line)
      const blankIndex = current.findIndex(line => !line.itemId)
      const nextLine = { itemId: String(item.itemId), quantity: '1', unitPrice: String(item.sellPrice ?? 0) }
      return blankIndex >= 0 && current.length === 1 ? [nextLine] : [...current, nextLine]
    })
    setItemSearch('')
  }
  async function save() { setMessage(''); if (!treasuryId || (saleType === 'CUSTOMER' && !customerId) || !lines.every(line => line.itemId && Number(line.quantity) > 0 && Number(line.unitPrice) >= 0)) { setMessage(ar ? 'أكمل الخزنة ونوع البيع والعناصر.' : 'Complete the treasury, sale type, and lines.'); return } setSaving(true); try { const response = await fetch('/api/sales', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ saleDate: new Date().toISOString().slice(0, 10), customerPartnerId: saleType === 'CUSTOMER' ? Number(customerId) : null, treasuryId: Number(treasuryId), currencyId: primaryCurrency?.currencyId, branchId, savedBy: userId, discount: Number(discount) || 0, lines: lines.map(line => ({ itemId: Number(line.itemId), quantity: Number(line.quantity), unitPrice: Number(line.unitPrice) })) }) }); if (!response.ok) throw new Error(await response.text()); const result = await response.json() as { saleNo: string }; setMessage(`${ar ? 'تم حفظ الفاتورة' : 'Invoice saved'}: ${result.saleNo}`); resetSale(); setNewSale(false); setRows(await (await fetch('/api/sales')).json()) } catch (error) { setMessage(error instanceof Error ? error.message : (ar ? 'تعذر حفظ البيع.' : 'Could not save sale.')) } finally { setSaving(false) } }
  if (loading) return <LoadingState />
  if (!newSale) return <div className="settings-page" dir={ar ? 'rtl' : 'ltr'}><PageHeader eyebrow={ar ? 'المبيعات' : 'SALES'} title={ar ? 'المبيعات' : 'Sales'} description={ar ? 'إدارة فواتير البيع وحركة المخزون والحسابات.' : 'Manage sales invoices, stock movement, and accounting.'} actions={<Button variant="primary" onClick={() => { resetSale(); setNewSale(true) }}>＋ {ar ? 'فاتورة جديدة' : 'New invoice'}</Button>} />{message && <div className="form-error" role="alert">{message}</div>}<Card><div className="table-frame"><table className="data-table"><thead><tr><th>{ar ? 'الفاتورة' : 'Invoice'}</th><th>{ar ? 'التاريخ' : 'Date'}</th><th>{ar ? 'النوع' : 'Type'}</th><th>{ar ? 'العميل' : 'Customer'}</th><th>{ar ? 'الإجمالي' : 'Total'}</th></tr></thead><tbody>{rows.map(row => <tr key={row.saleNo}><td>{row.saleNo}</td><td>{row.saleDate.slice(0, 10)}</td><td>{row.customerName ? (ar ? 'عميل' : 'Customer') : (ar ? 'مباشر' : 'Direct')}</td><td>{row.customerName ?? (ar ? 'بيع مباشر' : 'Walk-in')}</td><td>{row.total.toLocaleString()} {row.currencySymbol}</td></tr>)}{!rows.length && <tr><td colSpan={5}>{ar ? 'لا توجد فواتير بيع.' : 'No sales invoices yet.'}</td></tr>}</tbody></table></div></Card></div>
  const visibleItems = items.filter(item => `${item.itemCode} ${item.nameEn} ${item.nameAr}`.toLocaleLowerCase().includes(itemSearch.toLocaleLowerCase().trim()))
  const currencySymbol = primaryCurrency?.symbol ?? ''
  return <div className="settings-page" dir={ar ? 'rtl' : 'ltr'}>
    <PageHeader eyebrow={ar ? 'المبيعات' : 'SALES'} title={ar ? 'فاتورة بيع جديدة' : 'New sales invoice'} actions={<Button variant="secondary" onClick={() => { resetSale(); setNewSale(false) }}>← {ar ? 'العودة للفواتير' : 'Back to invoices'}</Button>} />
    {message && <div className="form-error" role="alert">{message}</div>}
    <Card className="sales-editor-card">
      <section className="sales-items-panel" aria-label={ar ? 'عناصر الفاتورة' : 'Invoice items'}>
        <div className="sales-panel-heading"><div><span className="sales-panel-icon" aria-hidden="true">▤</span><h2>{ar ? 'العناصر' : 'Items'}</h2></div><SearchInput value={itemSearch} onChange={event => setItemSearch(event.target.value)} onKeyDown={handleItemSearchKeyDown} placeholder={ar ? 'ابحث بالاسم أو امسح الباركود...' : 'Search item or scan barcode...'} aria-label={ar ? 'البحث أو مسح الباركود' : 'Search or scan barcode'} /></div>
        <div className="sales-table-wrap"><table className="data-table sales-lines-table"><thead><tr><th>{ar ? 'العنصر' : 'Item'}</th><th>{ar ? 'الوحدة' : 'Unit'}</th><th>{ar ? 'الكمية' : 'Qty'}</th><th>{ar ? 'السعر' : 'Price'}</th><th>{ar ? 'الإجمالي' : 'Total'}</th><th aria-label={ar ? 'إجراءات' : 'Actions'} /></tr></thead><tbody>
          {lines.map((line, index) => <tr key={index}><td><Select value={line.itemId} onChange={event => selectItem(index, event.target.value)}><option value="">{ar ? 'اختر العنصر' : 'Choose item'}</option>{visibleItems.map(item => <option key={item.itemId} value={item.itemId}>{ar ? item.nameAr : item.nameEn}</option>)}</Select></td><td><span className="sales-unit-cell">—</span></td><td><TextInput type="number" min="0.01" value={line.quantity} onChange={event => setLines(current => current.map((item, rowIndex) => rowIndex === index ? { ...item, quantity: event.target.value } : item))} aria-label={`${ar ? 'كمية العنصر' : 'Item quantity'} ${index + 1}`} /></td><td><TextInput type="number" min="0" value={line.unitPrice} onChange={event => setLines(current => current.map((item, rowIndex) => rowIndex === index ? { ...item, unitPrice: event.target.value } : item))} aria-label={`${ar ? 'سعر العنصر' : 'Item price'} ${index + 1}`} /></td><td className="sales-line-total">{((Number(line.quantity) || 0) * (Number(line.unitPrice) || 0)).toLocaleString()} {currencySymbol}</td><td><Button variant="ghost" className="sales-remove-button" aria-label={ar ? 'حذف العنصر' : 'Remove item'} onClick={() => setLines(current => current.length > 1 ? current.filter((_, rowIndex) => rowIndex !== index) : current)}>⌫</Button></td></tr>)}
        </tbody></table></div>
        {!lines.some(line => line.itemId) && <div className="sales-empty-state" role="status"><span className="sales-empty-icon" aria-hidden="true">◇</span><strong>{ar ? 'لم تتم إضافة عناصر بعد' : 'No items added yet'}</strong><span>{ar ? 'ابحث أو امسح الباركود لإضافة عنصر.' : 'Search or scan a barcode to add an item.'}</span><Button variant="outline" onClick={() => setLines(current => [...current, { itemId: '', quantity: '1', unitPrice: '0' }])}>＋ {ar ? 'إضافة عنصر' : 'Add item'}</Button></div>}
        <Button className="sales-add-row-button" variant="secondary" onClick={() => setLines(current => [...current, { itemId: '', quantity: '1', unitPrice: '0' }])}>＋ {ar ? 'إضافة عنصر' : 'Add item'}</Button>
      </section>
      <aside className="sales-summary-panel"><div className="sales-panel-heading sales-summary-heading"><div><span className="sales-panel-icon" aria-hidden="true">⚙</span><h2>{ar ? 'بيانات البيع' : 'Sale details'}</h2></div></div><FormField label={ar ? 'نوع البيع' : 'Sale type'} required><div className="sales-type-switch" role="group" aria-label={ar ? 'نوع البيع' : 'Sale type'}><button type="button" className={saleType === 'DIRECT' ? 'is-active' : ''} onClick={() => { setSaleType('DIRECT'); setCustomerId('') }}>🛒 <span>{ar ? 'بيع مباشر' : 'Direct sale'}</span></button><button type="button" className={saleType === 'CUSTOMER' ? 'is-active' : ''} onClick={() => setSaleType('CUSTOMER')}>♙ <span>{ar ? 'بيع لعميل' : 'Customer sale'}</span></button></div></FormField>{saleType === 'CUSTOMER' && <FormField label={ar ? 'العميل' : 'Customer'} required><Select value={customerId} onChange={event => setCustomerId(event.target.value)}><option value="">{ar ? 'اختر العميل' : 'Choose customer'}</option>{partners.filter(partner => partner.partnerTypeCode === 'CLIENT' || partner.partnerTypeCode === 'BOTH' || !partner.partnerTypeCode).map(partner => <option key={partner.partnerId} value={partner.partnerId}>{partner.partnerName}</option>)}</Select></FormField>}<FormField label={ar ? 'الخزنة' : 'Treasury'} required><Select value={treasuryId} onChange={event => setTreasuryId(event.target.value)}><option value="">{ar ? 'اختر الخزنة' : 'Choose treasury'}</option>{treasuries.map(item => <option key={item.treasuryId} value={item.treasuryId}>{ar ? item.nameAr : item.nameEn} · {item.currencySymbol}</option>)}</Select></FormField><FormField label={ar ? 'الخصم' : 'Discount'}><div className="sales-discount-input"><span aria-hidden="true">%</span><TextInput type="number" min="0" value={discount} onChange={event => setDiscount(event.target.value)} /><span>{currencySymbol}</span></div></FormField><div className="sales-summary-divider" /><dl className="sales-totals"><div><dt>{ar ? 'الإجمالي الفرعي' : 'Subtotal'}</dt><dd>{subtotal.toLocaleString()} {currencySymbol}</dd></div><div><dt>{ar ? 'الضريبة' : 'Tax'}</dt><dd>0 {currencySymbol}</dd></div></dl><div className="sales-total-row"><strong>{ar ? 'الإجمالي' : 'Total'}</strong><strong>{total.toLocaleString()} {currencySymbol}</strong></div><div className="sales-summary-actions"><Button variant="secondary" onClick={() => { resetSale(); setNewSale(false) }}>{ar ? 'إلغاء' : 'Cancel'}</Button><Button variant="primary" loading={saving} onClick={() => void save()}>▣ {ar ? 'حفظ الفاتورة' : 'Save invoice'}</Button></div></aside>
    </Card>
  </div>
}
